language: r
warnings_are_errors: true
sudo: false
cache: packages
use_bioc: true
bioc_required: true
r: release
before_install:
- wget -O antsr_travis.sh http://bit.ly/antsr_travis_sh
- cat antsr_travis.sh
- source ./antsr_travis.sh
- rm antsr_travis.sh
env:
  global: RGL_USE_NULL=TRUE
after_success:
- Rscript -e 'covr::coveralls()'
- install_build_with_tag


deploy:
  provider: releases
  skip_cleanup: yes
  api_key:
    secure: B8PHICus64jr1SxUo4Ge/bgYucaBkzkbWqz1D524LA8tycKapxRWI5IT7wn0/Vyo/rcwM5BAzXy9y7lLrvRLVnHfqawAJ0PeNmm2iYQt3QFP/2nPqW7+dcgPBnEk/r07e+qqVt9H2k+nNvlJEddjvGPTOcc4VFsUWy4Pfw8czNk=
  file_glob: yes
  file: extrantsr*.t*gz
  on:
    tags: yes
    repo: muschellij2/extrantsr