language: r
warnings_are_errors: true
sudo: false
cache: packages
use_bioc: true
bioc_required: true
r: release

os:
  - linux
  - osx

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran --install-args=--build"

before_install:
  - export PROJ_DIR=`basename $PWD`    
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - remove_neuroc_packages 
  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
  # does all the clang exports
  - x=`export_clang_cxx`; eval ${x}
  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
  - clang_cxx  
  - export cmake_version="3.11"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version
  - export ants_user=ANTsX
  - install_missing_remote_deps stnava/ITKR
  - install_missing_remote_deps ${ants_user}/ANTsRCore ${ants_user}/ANTsR
  - echo "Done Installing Missing Deps"
  - gh_binary_install stnava/ITKR
  - gh_binary_install ${ants_user}/ANTsRCore
  - gh_binary_install ${ants_user}/ANTsR  
  - cat DESCRIPTION
  - install_remotes_no_dep
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`

after_success:
  - Rscript -e 'covr::coveralls(type = "all")'

deploy:
  provider: releases
  skip_cleanup: yes
  api_key:
    secure: B8PHICus64jr1SxUo4Ge/bgYucaBkzkbWqz1D524LA8tycKapxRWI5IT7wn0/Vyo/rcwM5BAzXy9y7lLrvRLVnHfqawAJ0PeNmm2iYQt3QFP/2nPqW7+dcgPBnEk/r07e+qqVt9H2k+nNvlJEddjvGPTOcc4VFsUWy4Pfw8czNk=
  file_glob: yes
  file: extrantsr*.t*gz
  on:
    tags: yes
    repo: muschellij2/extrantsr
