# Sample .travis.yml for R projects

before_install:
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    
language: r
warnings_are_errors: true
sudo: required

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

r_github_packages:
 - stnava/cmaker
 - stnava/ITKR
 - stnava/ANTsR
