# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: false
cache: packages
use_bioc: yes
bioc_required: yes

r:
  - release

  
before_install:
  # for RGL
  - Rscript -e 'x = system("hostname", intern = TRUE); print(x);'
  - Rscript -e 'x = system("users", intern = TRUE); print(x);'
  - Rscript -e 'x = Sys.getenv("USER"); print(x);'
  - wget -O full_antsr_travis.sh http://bit.ly/full_antsr_travis
  - chmod +x full_antsr_travis.sh
  - . ./full_antsr_travis.sh  
  - rm full_antsr_travis.sh  

env:
  global:
    RGL_USE_NULL=TRUE

after_success:
  - Rscript -e 'covr::coveralls()'    